"""Export endpoint: notes as PDF / Markdown, flashcards as Anki CSV."""

import re
from typing import Literal
from urllib.parse import quote

from fastapi import APIRouter, Depends, Query, Response

from app.api.deps import get_lecture_or_404
from app.api.errors import api_error
from app.db.models import Lecture
from app.export.anki import flashcards_to_anki_csv
from app.export.pdf import notes_to_pdf
from app.generators.markdown import notes_to_markdown
from app.generators.schemas import FlashcardDeck, LectureNotes

router = APIRouter(prefix="/api/lectures/{lecture_id}", tags=["export"])

MEDIA_TYPES = {"pdf": "application/pdf", "md": "text/markdown; charset=utf-8", "csv": "text/csv; charset=utf-8"}


def _content_disposition(title: str, suffix: str, extension: str) -> str:
    """Download header with an ASCII filename plus the full Unicode name (for Hindi titles)."""
    base = f"{title} - {suffix}"
    ascii_name = re.sub(r"[^A-Za-z0-9]+", "-", base).strip("-")[:80] or "lecture"
    return f"attachment; filename=\"{ascii_name}.{extension}\"; filename*=UTF-8''{quote(f'{base}.{extension}')}"


def _subtitle(lecture: Lecture) -> str:
    duration = f"{max(1, round(lecture.duration_seconds / 60))} min" if lecture.duration_seconds else None
    return "  ·  ".join(p for p in (lecture.channel, duration) if p)


@router.get("/export")
def export_lecture(
    lecture: Lecture = Depends(get_lecture_or_404),
    format: Literal["pdf", "md", "csv"] = Query(..., description="pdf / md = notes, csv = flashcards for Anki"),
) -> Response:
    """Download the lecture's notes or flashcards as a file."""
    if lecture.status != "done" or not lecture.notes_json or not lecture.flashcards_json:
        raise api_error(409, "This lecture hasn't finished processing yet.")

    video_url = lecture.url if lecture.source_type == "youtube" else None
    if format == "csv":
        deck = FlashcardDeck.model_validate_json(lecture.flashcards_json)
        content: bytes | str = flashcards_to_anki_csv(deck.cards, lecture.title, video_url)
        disposition = _content_disposition(lecture.title, "flashcards", "csv")
    else:
        notes = LectureNotes.model_validate_json(lecture.notes_json)
        if format == "md":
            header = f"> Source: {lecture.title}" + (f" ({video_url})" if video_url else "")
            if _subtitle(lecture):
                header += f" · {_subtitle(lecture)}"
            content = f"{header}\n> Generated by LectureLens\n\n{notes_to_markdown(notes, video_url=video_url)}"
        else:
            content = notes_to_pdf(notes, lecture.title, video_url=video_url, subtitle=_subtitle(lecture))
        disposition = _content_disposition(lecture.title, "notes", format)

    return Response(content=content, media_type=MEDIA_TYPES[format], headers={"Content-Disposition": disposition})
